// 서버측 API 구현 이슈로 인해 mock data 임시 진행

import { Post } from '@/features/board/shared/types/DefaultPostType';
import {
  PostCategory,
  PostType,
} from '@/features/board/shared/types/enum/postEnum';

export const mockPosts: Post[] = [
  {
    id: 1,
    title: '삼성전자 신입 면접 후기 공유합니다',
    content:
      '오늘 삼성전자 SW 직군 면접을 봤는데요, 자료구조와 알고리즘 위주로 질문이 들어왔습니다. 특히 해시테이블과 트리 구조에 대해 깊게 물어보셨어요.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.INTERVIEW,
    firstMajorName: '컴퓨터공학과',
    secondMajorName: '경영학과',
    likeCount: 45,
    commentCount: 12,
    bookmarkCount: 8,
    createdAt: '2025-01-15T10:30:00',
  },
  {
    id: 2,
    title: '네이버 인턴십 합격했어요!',
    content:
      '네이버 클로바 팀 인턴십에 최종 합격했습니다. 코딩테스트는 백준 골드 수준이었고, 면접에서는 프로젝트 경험을 많이 물어보셨어요.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.INTERNSHIP,
    firstMajorName: '소프트웨어학과',
    secondMajorName: '',
    likeCount: 128,
    commentCount: 34,
    bookmarkCount: 56,
    createdAt: '2025-01-14T15:20:00',
  },
  {
    id: 3,
    title: '정보처리기사 필기 합격 후기',
    content:
      '정보처리기사 필기 시험 합격했습니다! 기출문제 3개년치만 반복해서 풀었는데 충분했어요. 특히 데이터베이스와 소프트웨어 공학 파트가 중요합니다.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.LICENSE,
    firstMajorName: '정보통신공학과',
    secondMajorName: '',
    likeCount: 67,
    commentCount: 19,
    bookmarkCount: 42,
    createdAt: '2025-01-13T09:15:00',
  },
  {
    id: 4,
    title: '카카오 신입 개발자 실무 이야기',
    content:
      '카카오에 입사한 지 6개월 됐습니다. 실무에서는 학교에서 배운 것보다 코드 리뷰와 협업 능력이 더 중요하다는 걸 느꼈어요.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.EXPERIENCE,
    firstMajorName: '컴퓨터공학과',
    secondMajorName: '',
    likeCount: 89,
    commentCount: 27,
    bookmarkCount: 33,
    createdAt: '2025-01-12T14:45:00',
  },
  {
    id: 5,
    title: '토스 채용 공고 떴어요!',
    content:
      '토스에서 2025 상반기 신입 개발자를 모집한다고 합니다. 지원 마감은 이번 달 말까지고, 코딩테스트는 프로그래머스에서 진행됩니다.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.JOB,
    firstMajorName: '전자공학과',
    secondMajorName: '컴퓨터공학과',
    likeCount: 156,
    commentCount: 41,
    bookmarkCount: 78,
    createdAt: '2025-01-11T11:00:00',
  },
  {
    id: 6,
    title: '구글 대학생 개발자 컨퍼런스 다녀왔어요',
    content:
      '구글에서 주최한 대학생 개발자 컨퍼런스에 다녀왔습니다. 최신 AI 기술 트렌드와 실무 개발자들의 이야기를 들을 수 있었어요.',
    category: PostCategory.EXTERNAL_ACTIVITIES,
    type: PostType.EXPERIENCE,
    firstMajorName: '인공지능학과',
    secondMajorName: '',
    likeCount: 203,
    commentCount: 52,
    bookmarkCount: 91,
    createdAt: '2025-01-10T16:30:00',
  },
  {
    id: 7,
    title: 'AWS 솔루션즈 아키텍트 자격증 취득 팁',
    content:
      'AWS SAA 자격증 취득했습니다! 인강은 스터디윗미 강의 들었고, 덤프 문제 2회독 했어요. 실습 경험이 있으면 훨씬 수월합니다.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.LICENSE,
    firstMajorName: '컴퓨터공학과',
    secondMajorName: '',
    likeCount: 94,
    commentCount: 23,
    bookmarkCount: 67,
    createdAt: '2025-01-09T13:20:00',
  },
  {
    id: 8,
    title: '라인 플러스 면접 질문 정리',
    content:
      '라인 플러스 백엔드 직군 면접 봤습니다. 기술 면접에서는 Spring Framework, JPA, Redis 관련 질문이 많았고, 인성 면접은 부드러운 분위기였어요.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.INTERVIEW,
    firstMajorName: '소프트웨어학과',
    secondMajorName: '수학과',
    likeCount: 112,
    commentCount: 28,
    bookmarkCount: 45,
    createdAt: '2025-01-08T10:50:00',
  },
  {
    id: 9,
    title: '쿠팡 인턴 생활 후기',
    content:
      '쿠팡에서 3개월 인턴으로 일했습니다. MSA 환경에서 실무 경험을 쌓을 수 있었고, 멘토링 프로그램도 잘 되어있어요. 야근은 거의 없었습니다.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.INTERNSHIP,
    firstMajorName: '컴퓨터공학과',
    secondMajorName: '',
    likeCount: 178,
    commentCount: 47,
    bookmarkCount: 83,
    createdAt: '2025-01-07T15:10:00',
  },
  {
    id: 10,
    title: '현직 개발자가 말하는 취업 준비 로드맵',
    content:
      '네이버에서 5년차 백엔드 개발자입니다. 취업 준비생들을 위해 로드맵을 정리해봤어요. CS 기초 → 알고리즘 → 프로젝트 → 면접 준비 순서를 추천합니다.',
    category: PostCategory.JOB_INFORMATION,
    type: PostType.EXPERIENCE,
    firstMajorName: '컴퓨터공학과',
    secondMajorName: '',
    likeCount: 342,
    commentCount: 89,
    bookmarkCount: 156,
    createdAt: '2025-01-06T09:00:00',
  },
];
