// 삭제 예정
// API 구현 전 임시 mock data
export const mockBoardPosts = [
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '토스 인턴 넣으신분?',
    content: '나 어제 넣었는데 서류에서 광탈할것같긴한데 넣어봤어...',
    author: '익명',
    major: '컴퓨터공학과',
    time: '18:56',
    likes: 40,
    comments: 12,
  },
  {
    category1: '대외활동',
    category2: '공모전',
    title: '요즘 뜨는 공모전 뭐 있어요?',
    content: '여름방학 때 할만한 공모전 추천 좀 부탁드려요!',
    author: '익명',
    major: '경영학과',
    time: '12:20',
    likes: 22,
    comments: 5,
    scrab: 30,
  },
  {
    category1: '취업정보',
    category2: '면접',
    title: '카카오 면접 후기 공유합니다',
    content: '면접 분위기는 편했는데 질문이 예상외였어요...',
    author: '익명',
    major: '전자공학과',
    time: '14:02',
    likes: 35,
    comments: 8,
  },
  {
    category1: '학교생활',
    category2: '강의평가',
    title: '자료구조 수업 어때요?',
    content: '이번에 들으려고 하는데 교수님 스타일이 어떤지 궁금합니다.',
    author: '익명',
    major: '소프트웨어학과',
    time: '09:45',
    likes: 12,
    comments: 3,
  },
  {
    category1: '취업정보',
    category2: '채용공고',
    title: 'LG 신입 공고 올라왔네요',
    content: '서류 마감일이 이번 주 금요일이래요. 얼른 확인하세요!',
    author: '익명',
    major: '산업공학과',
    time: '11:10',
    likes: 18,
    comments: 7,
  },
  {
    category1: '자유게시판',
    category2: '잡담',
    title: '요즘 날씨 미쳤다',
    content: '아침에는 추운데 낮에는 덥고... 옷 고르기 너무 힘들다.',
    author: '익명',
    major: '심리학과',
    time: '16:22',
    likes: 27,
    comments: 9,
  },
  {
    category1: '취업정보',
    category2: '인턴십',
    title: '삼성 인턴 서류 발표 났나요?',
    content: '메일이 안 와서 혹시 발표 확인하신 분 계신가요?',
    author: '익명',
    major: '경영학과',
    time: '10:18',
    likes: 33,
    comments: 14,
  },
  {
    category1: '대외활동',
    category2: '봉사활동',
    title: '해외 봉사활동 모집 소식',
    content: '겨울방학에 라오스 봉사활동 팀 모집 중이래요.',
    author: '익명',
    major: '사회복지학과',
    time: '13:33',
    likes: 15,
    comments: 6,
  },
  {
    category1: '학교생활',
    category2: '동아리',
    title: '개발 동아리 신입 모집합니다',
    content: '프론트엔드, 백엔드 다 모집하니 관심 있는 분들 지원하세요!',
    author: '익명',
    major: '컴퓨터공학과',
    time: '17:40',
    likes: 45,
    comments: 20,
  },
  {
    category1: '취업정보',
    category2: '면접',
    title: 'IT 스타트업 면접 질문 공유',
    content: 'JS 비동기 관련 질문 많이 나왔습니다. 준비하세요!',
    author: '익명',
    major: '정보통신공학과',
    time: '15:55',
    likes: 28,
    comments: 11,
  },
];
